### PR TITLE
Update bing key

### PR DESCRIPTION
**Pull request by gberaudo**
Update the OpenLayers Bing key for the online examples:
http://openlayers.org/ol3-cesium/examples/

### CODE REVIEW

**Comment by gberaudo** [comment]
See https://github.com/openlayers/ol3/pull/4691

**Comment by ahocevar** [comment]
Please don't use the OpenLayers API key. We need to be very restrictive with the use of that key, to avoid that we go over quota.

**Comment by tschaub** [comment]
I agree it would be best to restrict this key to use in the OpenLayers examples only.  Keys are freely available at https://www.bingmapsportal.com/, so I'd suggest registering for a dedicated ol3-cesium one.

**Comment by gberaudo** [comment]
Thanks for the feedbacks @ahocevar and @tschaub.

**Pull request closed without merging**
