### PR TITLE
Port to OpenLayers 3.18.1

### PR DESCRIPTION
**Pull request by gberaudo**

### CODE REVIEW

**Comment by ahocevar** [comment]
Don't you want to wait for OpenLayers v3.18.1? It will have fixes for at least two regressions that were reported.

**Comment by gberaudo** [comment]
Thanks @ahocevar for notifying me. Do we already have an ETA?
Cesium will come on Thursday; I can certainly wait until next week for the portings.

**Comment by ahocevar** [comment]
That should be fine. One of the two fixes is already merged, the other is awaiting review. So I'm expecting OpenLayers 3.18.1 to be out today or tomorrow.

**Comment by gberaudo** [comment]
Great! thanks.

**Comment by gberaudo** [comment]
Updated with 3.18.1. See https://github.com/openlayers/ol3/pull/5803.

**Comment by gberaudo** [comment]
OK, I think this PR makes consensus. Merging it now.
Thanks @ahocevar for being so fast publishing the OL3 patch version.

**Pull request merged**
