### PR TITLE
Make sure dist is present in package published on npm

### PR DESCRIPTION
**Pull request by gberaudo**
See https://www.npmjs.com/package/ol3-cesium.

### CODE REVIEW

**Comment by ahocevar** [comment]
The change does not do what the title suggests. Wrong branch maybe?

**Comment by gberaudo** [comment]
No it is correct. The .npmignore takes precedence over the .gitignore.

**Comment by ahocevar** [comment]
Ah ok. Now I see what you were trying to do. Alright! 👍

**Comment by gberaudo** [comment]
Thanks for the review @ahocevar.

**Pull request merged**
