### PR TITLE
Set billboard opacity

### PR DESCRIPTION
**Pull request by gberaudo**
Handle opacity property in the converter.

### CODE REVIEW

**Comment by ahocevar** [comment]
Looks good. Please merge.

**Comment by schmidtk** [comment]
This works if the opacity is set at the style level, but it may be set at the layer level. Are there plans to handle that case?

**Comment by gberaudo** [comment]
Unfortunately, this OL3 mechanism does not have equivalent in Cesium.
A good solution would avoid destroying and recreating all primitives.
It would require Ol3 to propagate layer changes in a finer way.

**Comment by ahocevar** [comment]
I'll take a look. Maybe there is a way.

**Comment by ahocevar** [comment]
@schmidtk As far as I can tell, this change also works for an opacity set on the layer level. The style that is queried for the opacity still comes from `olcs.core.computePlainStyle`, which takes both feature and layer styles into account and executes the style function for each feature. Can you confirm?

**Comment by ahocevar** [comment]
I see now what you mean @schmidtk: an opacity set by `ol.layer.Base#setOpacity`. I'll see if I can come up with something.

**Comment by ahocevar** [comment]
@schmidtk I came up with #166 for layer opacity support.

**Pull request merged**
