### PR TITLE
Allow applications to use custom synchronizers

### PR DESCRIPTION
**Pull request by ahocevar**
This is a revised version of #147 and replaces #150.

Thanks for any review.

### CODE REVIEW

**Comment by gberaudo** [comment]
Looks very good to me @ahocevar. Thank you for the effort; please merge.

**Comment by ahocevar** [comment]
Thanks for the review @gberaudo.

**Comment by tschaub** [comment]
Sentimental versioning FTW!

**Comment by tschaub** [comment]
I don't have a dog in this fight, but what's the justification for not calling this 2.0?  Version numbers are cheap.

**Comment by ahocevar** [comment]
@tschaub See #149 for the discussion.

**Pull request merged**
