### PR TITLE
Verify the feature is still displayed on the map before creating the …

### PR DESCRIPTION
**Pull request by oterral**
…billboard

@gberaudo if you have a better idea (go through all the features of the source) to test if the feature is still displayed on the map, I take it.

### CODE REVIEW

**Comment by gberaudo** [comment]
Hi @oterral, I would prefer to avoid the graph traversal in rbush + creation of an array + iteration over all features.
We could listen on the source for clear and feature removal event and cancel the creation of the billboard.
I had a try, see https://github.com/openlayers/ol3/pull/4243 and https://github.com/oterral/ol3-cesium/compare/loadbill...gberaudo:loadbill.

**Comment by oterral** [comment]
@gberaudo yes you 've a much better solution. I test it.

**Comment by oterral** [comment]
@gberaudo [here](https://github.com/oterral/ol3-cesium/compare/loadbill...gberaudo:loadbill#diff-055a625e546d9fc23902a2db70d609f1R535) the clear event doesn't exist on `layer`, shouldn't we listen on `source.on['removefeature', 'clear' ... `  ?

**Comment by oterral** [comment]
Listening the source events it works as expected.

**Comment by gberaudo** [comment]
Right @oterral, I meant to listen on the source.

**Comment by oterral** [comment]
@gberaudo will you make a PR with your branch ?

**Comment by gberaudo** [comment]
Thank you @oterral for spotting the issue. It is really nice to have this fixed.

**Pull request closed without merging**
