### PR TITLE
Fix typo 'ineartia' to 'inertia'.

### PR DESCRIPTION
**Pull request by poppycocker**
Fixed a typo.

### CODE REVIEW

**Comment by fredj** [comment]
Good catch!
Can you please also change the [externs](https://github.com/openlayers/ol3-cesium/blob/master/Cesium.externs.js#L2546)?

**Comment by poppycocker** [comment]
Oh, I overlooked that.
Updated a little while ago, please check it out.

**Comment by gberaudo** [comment]
Hi @poppycocker, thank you for the PR.
Could you please merge the two commits together?
You may do this with:
```
git reset HEAD^
git add Cesium.externs.js
git commit --amend
```

**Comment by poppycocker** [comment]
Okay. I typed commands above, and did some merges to push...
Would this be OK?

**Comment by gberaudo** [comment]
After the above commands you should have force pushed to your branch.
I merged your code in #263; thank you for the PR.

**Comment by poppycocker** [comment]
That makes sense then... I will study more about Git.
Thank you for helping me!!

**Pull request closed without merging**
