### PR TITLE
Fix test to createShadowVolume property

### PR DESCRIPTION
**Pull request by gberaudo**
Should fix https://github.com/openlayers/ol3-cesium/issues/329.

### CODE REVIEW

**Comment by fredj** [comment]
LGTM

**Comment by oterral** [comment]
when cesium is compiled, isn't `createShadowVolume` changed  to a smaller name?

**Comment by oterral** [comment]
Thx for the quick fix.

**Comment by gberaudo** [comment]
Thanks for the review.

**Pull request merged**
