### PR TITLE
Remove use of goog.events

### PR DESCRIPTION
**Pull request by oterral**

### CODE REVIEW

**Comment by gberaudo** [comment]
Thanks @oterral, this is almont working.
You need to remove `goog.isArray` from `build/check-no-goog.sh`.
And I created https://github.com/openlayers/ol3/issues/4845 to fix the geolocation error.

Once this is done, OL3-Cesium builds without error.

**Comment by oterral** [comment]
Awesome thx @gberaudo

**Comment by oterral** [comment]
@gberaudo can you review? the build should pass now

**Comment by gberaudo** [comment]
Great, thanks.

**Pull request merged**
